apiVersion: v1
description: A Helm chart for Docker Registry
name: proxy-registry
version: 3.0.7
appVersion: 3.0.1
home: https://hub.docker.com/_/registry/
icon: https://helm.twun.io/docker-registry.png
maintainers:
- email: anshul.thakkar@tmdc.io
  name: Anshul Thakkar
sources:
- https://github.com/docker/distribution-library-image
